# G2_TAG_INVENTORY = 0x01
# G2_READ_DATA = 0x02
# G2_WRITE_DATA = 0x03
# G2_WRITE_EPC = 0x04
# G2_KILL_TAG = 0x05
# G2_SET_PROTECTION = 0x06
# G2_ERASE_BLOCK = 0x07
# G2_READ_PROTECTION_EPC = 0x08
# G2_READ_PROTECTION_NO_EPC = 0x09
# G2_UNLOCK_READ_PROTECTION = 0x0a
# G2_READ_PROTECTION_STATUS_CHECK = 0x0b
# G2_EAS_CONFIGURATION = 0x0c
# G2_EAS_ALERT_DETECTION = 0x0d
# G2_SINGLE_TAG_INVENTORY = 0x0f
# G2_WRITE_BLOCKS = 0x10
# G2_GET_MONZA_4QT_WORKING_PARAMETERS = 0x11
# G2_SET_MONZA_4QT_WORKING_PARAMETERS = 0x12
# G2_READ_EXTENDED_DATA = 0x15
# G2_WRITE_EXTENDED_DATA = 0x16
# G2_TAG_INVENTORY_WITH_MEMORY_BUFFER = 0x18
# G2_MIX_INVENTORY = 0x19
# G2_INVENTORY_EPC = 0x1a
# G2_QT_INVENTORY = 0x1b

# CF_GET_READER_INFO = 0x21
# CF_SET_WORKING_FREQUENCY = 0x22
# CF_SET_READER_ADDRESS = 0x24
# CF_SET_READER_INVENTORY_TIME = 0x25
# CF_SET_SERIAL_BAUD_RATE = 0x28
# CF_SET_RF_POWER = 0x2f
# CF_SET_WORK_MODE_288M = 0x76
# CF_SET_WORK_MODE_18 = 0x35
# CF_SET_BUZZER_ENABLED = 0x40
# CF_SET_ACCOUSTO_OPTIC_TIMES = 0x33

from dataclasses import dataclass


@dataclass
class Command:
    code: int
    type_: int

    def to_bytearray(self) -> bytearray:
        return bytearray([self.code, self.type_])


SET_COMMAND = 0x31
GET_COMMAND = 0x32
COMMAND = 0x7c
RESPONSE = 0xcc


ISO_IDENTIFY = Command(code=0x01, type_=GET_COMMAND)
ISO_WRITE_DATA = Command(code=0x02, type_=SET_COMMAND)
ISO_READ_DATA = Command(code=0x02, type_=GET_COMMAND)


G2_IDENTIFY_SINGLE = Command(code=0x10, type_=GET_COMMAND)
G2_IDENTIFY_MULTI = Command(code=0x11, type_=GET_COMMAND)
G2_WRITE_DATA = Command(code=0x12, type_=SET_COMMAND)
G2_READ_DATA = Command(code=0x12, type_=GET_COMMAND)


SET_BASIC_SETTINGS = Command(code=0x81, type_=SET_COMMAND)
GET_BASIC_SETTINGS = Command(code=0x81, type_=GET_COMMAND)
SET_READER_ADDRESS = Command(code=0x82, type_=SET_COMMAND)
GET_READER_INFO = Command(code=0x82, type_=GET_COMMAND)
SOFTWARE_RESET = Command(code=0x8f, type_=SET_COMMAND)
G2_UNLOCK_READ_PROTECTION = Command(code=0x30, type_=SET_COMMAND)